name: Build OpenWrt VeloCloud

on:
  workflow_dispatch:

jobs:
  build:
    name: Compile Firmware
    runs-on: ubuntu-22.04

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc wget unzip python3 subversion

      - name: 3. Initialize & Update Submodules
        run: |
          git submodule init
          git submodule update

      - name: 4. Fix SVN Format & Update Feeds
        run: |
          cd trunk
          # Membuat folder kosong yang hilang agar SVN tidak komplain
          mkdir -p toolchain/binutils/patches/.svn/text-base
          # Tambahkan perintah ini jika masih error di folder lain
          mkdir -p toolchain/gcc/patches/.svn/text-base
          svn upgrade
          ./scripts/feeds update -a
          ./scripts/feeds install -a


      - name: 5. Konfigurasi Firmware
        run: |
          cp openwrt.config trunk/.config
          cd trunk
          make defconfig

      - name: 6. Download Packages
        run: |
          cd trunk
          make download -j8

      - name: 7. Proses Kompilasi
        run: |
          cd trunk
          make -j$(nproc) V=s

      - name: 8. Upload Hasil Kompilasi
        uses: actions/upload-artifact@v4
        with:
          name: compiled-firmware
          path: trunk/bin/targets/
